### ISSUE TITLE
No deployment error of the app tile, even the app fails to run

### ISSUE THREAD

**Issue by lizzha** [cf-platform-eng/tile-generator#191]
Deploy an app tile generated by tile-generator, the deployment succeeds even the app fails to run.

**Comment by joeeltgroth** [comment]
After assessing this, we think that tile-generator is working as expected.  The installation log will show that the deploy-all errand failed due the app failure.  Ops Manager shows the tile "green", and this is under control of Ops Manager rather than tile deployments.   It is up to the operator to decide next steps.
