### ISSUE TITLE
Possible pip requirements issue

### ISSUE THREAD

**Issue by guidowb** [cf-platform-eng/tile-generator#202]
I’m setting up the ability to dev on opsmanager instance because I’m on a plane and installing from pip and pip installed from apt-get I got this and this is how I fixed it:
```
pkg_resources.DistributionNotFound: six>=1.9
ubuntu@ip-10-0-0-210:~/redislabs-release/tile$ sudo pip install six
Requirement already satisfied (use --upgrade to upgrade): six in /usr/lib/python2.7/dist-packages
Cleaning up...
ubuntu@ip-10-0-0-210:~/redislabs-release/tile$ sudo pip install six --upgrade
Downloading/unpacking six from https://pypi.python.org/packages/c8/0a/b6723e1bc4c516cb687841499455a8505b44607ab535be01091c0f24f079/six-1.10.0-py2.py3-none-any.whl#md5=3ab558cf5d4f7a72611d59a81a315dc8
  Downloading six-1.10.0-py2.py3-none-any.whl
Installing collected packages: six
  Found existing installation: six 1.5.2
    Not uninstalling six at /usr/lib/python2.7/dist-packages, owned by OS
Successfully installed six
Cleaning up...
```

**Comment by mboldt** [comment]
Let me make sure I understand: the symptom was:
```
pkg_resources.DistributionNotFound: six>=1.9
```
The fix was to upgrade six. The root cause seems to be that pip let you install tile-generator without having a suitable version of six (which, iiuc, is a downstream dependency of some library tile-generator uses). Is that correct? Do you think we need to add a direct dependency on `six>=1.9`?

**Comment by keshto** [comment]
Please re-open if this issue is still affecting you.
