### ISSUE TITLE
Syntax error when deleting bosh_docker tile 

### ISSUE THREAD

**Issue by mdcarlson** [cf-platform-eng/tile-generator#21]
I created a simple test tile from a working docker image.  When I attempted to delete the tile from OpsMan, I received the following error.

`/var/vcap/jobs/delete-app-pact_broker_docker_app/bin/run: line 38: syntax error near unexpected token`if'`

I did not modify the generated delete-app script.

Happy to share additional details, if you'd tell me where to send them and what you need.

**Comment by sparameswaran** [comment]
Can you create a gist with the lines from the delete-app-pact_broker_app/templates/delete-app-pact_broker_app.sh.erb file?

**Comment by sparameswaran** [comment]
Can you also sync-up with the latest? quite possible you dont have latest changes.

**Comment by mdcarlson** [comment]
I am unable to locate `delete-app-pact_broker_app/templates/delete-app-pact_broker_app.sh.erb` in any of the folders in my tile working directory.   I do find `docker-bosh-pact_broker_docker_bosh_app.sh.erb` in `workspace/tile-generator/sample2/release/jobs/docker-bosh-pact_broker_docker_bosh_app/templates` folder, but that is the only *.erb file.

Can you point me in the right direction?

**Comment by guidowb** [comment]
Mark, Sabha, there's something odd here. It looks like the tile in the workspace has a docker-bosh type package, but docker-bosh packages do not have a delete-app-\* errand. Mark, is it possible that the tile you are trying to delete is an older version that had a docker-app type package instead of a docker-bosh one?

If that's the case, the only place where we will find the offending script is in the .pivotal file for that version, or on the Ops Manager VM.

**Comment by mdcarlson** [comment]
You're probably right.  My first attempt at this tile used a type of docker-app. 

Here is the delete script from that initial release of my test tile.

https://gist.github.com/mdcarlson/21b00cb04d9b95254c0e#file-delete-app-pact_broker_docker_app-sh-erb

**Comment by guidowb** [comment]
Yes, the for loop on line 49 is missing the do/done in your version. This has since been fixed (the current version in the repo looks correct).
Do you need help cleaning up the corrupt tile?

**Comment by mdcarlson** [comment]
Yes, that would be helpful.  I do know the unencyrpt/decrypt trick to manually update the installation.yml.

**Comment by sparameswaran** [comment]
Mark, sorry for the inconvenience. In your case, since you mainly have a docker-bosh type that does not have a real errand, turn off the post-delete errand on the tile page, save changes and then hit delete the tile. This should let bosh delete the deployment. Let me know if this works.

If its an app type, then we would have to run the bosh run errand manually with "--keep-alive" option and then go into the errand vm using bosh ssh, fix the script and let it re-run and complete. And then delete the release followed by clean up of the installation.yml file.

**Comment by mdcarlson** [comment]
Unchecking the post-delete errand did the trick.  I'll start fresh with my bosh_docker job type.
