### ISSUE TITLE
If you rename your package and then upgrade, the upgrade will leave detritus

### ISSUE THREAD

**Issue by bar-jakubovitz** [cf-platform-eng/tile-generator#31]
Scenario :
1. use tile generator to generate a tile.yml file
2. edit your tile.yml file
3. build a tile
4. import the tile to ops manager
5. deploy the tile (in my case, deployment of service broker failed on "cf create-service-broker" errand)
- at this point you should have a running instance of your tile service in CF.
- change the package name in your tile.yml file
- rebuild your tile
- import the new tile to ops manager
- upgrade your tile to the new version
- deploy changes
  (at this point the deployment still failed in the "cf create-service-broker" phase)
- at this point you should have 2 running apps (service brokers) in CF - the old artifacts are not being cleaned.

**Comment by guidowb** [comment]
Just adding thoughts about possible approaches:
- Find a way to tag all cf artifacts with a product name, so that we can always find them
- Historically track all artifacts (back to epoch since we support upgrades from any version X to any version Y)
- Refuse to allow name changes unless user also provides upgrade logic

**Comment by guidowb** [comment]
With the ability to add custom errand code to deploy-all, there is now a way to clean up the detritus if you choose to rename components of the tile. Since this is an uncommon case, we have no plan to automate this.
