### ISSUE TITLE
Random-route property defined is always overridden and route conflict occurs on deploying a tile unless route is not in use.

### ISSUE THREAD

**Issue by miyer-pivotal** [cf-platform-eng/tile-generator#37]
Error Observed: The 'route xxxxxxx is already in use' error occurs even if tile.yaml has random-route:true defined under properties: manifest

Possible cause: --HOSTNAME is being passed as a parameter and the random-route property is being overridden each time

Current hack to fix this:
Add host:<super unique name> under properties:manifest in tile.yml

Partial Error Trace:
Using route edb_postgresql.cfapps-02.haas-26.pez.pivotal.io
Binding edb_postgresql.cfapps-02.haas-26.pez.pivotal.io to edb_postgresql-0.0.6...
FAILED
The route edb_postgresql.cfapps-02.haas-26.pez.pivotal.io is already in use.
TIP: Change the hostname with -n HOSTNAME or use --random-route to generate a new route and then push again.

[stderr]
None

{"type": "step_finished", "id": "errands.running.hans-edb-broker-7a61ed19cfd379ef1542.deploy-all"}
Exited with 1.

**Comment by guidowb** [comment]
Just adding thoughts while considering how (or as it turns out, if) to fix this:

There are lots of dependencies on knowing the app name and route in the code generated by tile-generator:
- We do blue/green deployment when updating apps. This depends on the old and new versions sharing the same route
- We (attempt to) clean up old versions, which makes sense only when the new version uses the same route
- Management of dependencies between packages (like service bindings) rely on the package name being used for the route

I'm also struggling to come up with a valid use case for having a tile deploy something at a random route. Would anyone really want that?

So I'm thinking that we are really just trying to work around the cleanup issue documented in #31. If we properly cleaned up old versions using this route (even when you've changed the name or the org or space), you would not run into this issue. If the route really is already taken by a **different** tile, then we should fail gracefully, and the developer should choose a more unique name.

If you accept that reasoning, we'll have to do some doc and validation updates to make random-route explicitly unsupported.
