### ISSUE TITLE
Find a way to never require new stemcell uploads

### ISSUE THREAD

**Issue by guidowb** [cf-platform-eng/tile-generator#42]

**Comment by guidowb** [comment]
Findings:
- You cannot omit the stemcell_criteria in the tile metadata
- You cannot omit the version in the stemcell_criteria in the tile metadata
- You cannot parameterize the stemcell_criteria in the tile metadata

On the other hand:

You can write a little script against the OpsMgr API that re-configures an already uploaded and installed release to use the same stemcell as the cf product, which will cause it to turn green. This is what the pcf command does. So when using that command to install tiles, stemcell uploads are never required.

Trying to determine if this is somehow a sufficient solution...

**Comment by bingosummer** [comment]
@guidowb 
I think the following comments should be changed.
https://github.com/cf-platform-eng/tile-generator/blob/master/templates/tile.yml#L32-L35

Because if the version is not specified, the version will be `3146.5` which is not the latest stemcell version. So, I think, it should be required to configure the version except there's a way to always use the same version with the cf product.

**Comment by guidowb** [comment]
@bingosummer That makes sense, but a better alternative would be for us to fix the code so that it does what the comment says - always pick up the latest stemcell. I'm going to give that a try first.
